language: php
dist: trusty
php:
  - '7.3'
services:
  - mysql
install: composer install
after_success:
  # or enable logging
  #- travis_retry php vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash)